services:
  mongo-appointment:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_appointment_data:/data/db

  mysql-doctor:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_doctor_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  mysql-patient:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_patient_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  appointment-service:
    depends_on:
      - mongo-appointment
    image: sybren123/appointment-service
    ports:
      - 8080:8080
    links:
      - mongo-appointment
    environment:
      PATIENT_SERVICE_BASEURL: patient-service:8082
      DOCTOR_SERVICE_BASEURL: doctor-service:8081
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-appointment

  doctor-service:
    depends_on:
      - mysql-doctor
    image: sybren123/doctor-service
    ports:
      - 8081:8081
    links:
      - mysql-doctor
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-doctor
      MYSQL_DB_PORT: 3308

  patient-service:
    depends_on:
      - mysql-patient
    image: sybren123/patient-service
    ports:
      - 8082:8082
    links:
      - mysql-patient
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-patient
      MYSQL_DB_PORT: 3307

volumes:
  mongodb_appointment_data:
  mysql_doctor_data:
  mysql_patient_data: