global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'appointment_service'
    static_configs:
      - targets: [ 'appointment-service:8080' ]

  - job_name: 'doctor_service'
    static_configs:
      - targets: [ 'doctor-service:8081' ]

  - job_name: 'patient_service'
    static_configs:
      - targets: [ 'patient-service:8082' ]
