server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: appointment-service-all
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointments
            - Method=GET
          filters:
            - SetPath=/api/appointment/all
        - id: appointment-service
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointments
            - Method=POST
          filters:
            - SetPath=/api/appointment
        - id: appointment-service-update
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointments
            - Method=PUT
          filters:
            - SetPath=/api/appointment
        - id: appointment-service-delete
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointments
            - Method=DELETE
          filters:
            - SetPath=/api/appointment

        - id: doctor-service-all
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/doctors
            - Method=GET
          filters:
            - SetPath=/api/doctor/all
        - id: doctor-service
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/doctors
            - Method=POST
          filters:
            - SetPath=/api/doctor
        - id: doctor-service-update
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/doctors
            - Method=PUT
          filters:
            - SetPath=/api/doctor
        - id: doctor-service-delete
          uri: http://${DOCTOR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/doctors
            - Method=DELETE
          filters:
            - SetPath=/api/doctor
        - id: patient-service-all
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/patients
            - Method=GET
          filters:
            - SetPath=/api/patient/all
        - id: patient-service
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/patients
            - Method=POST
          filters:
            - SetPath=/api/patient
        - id: patient-service-update
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/patients
            - Method=PUT
          filters:
            - SetPath=/api/patient
        - id: patient-service-delete
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/patients
            - Method=DELETE
          filters:
            - SetPath=/api/patient